import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import nodemailer from "nodemailer";
import rateLimit from "express-rate-limit";
import { z } from "zod";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, (m) => map[m] || m);
}

const emailLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 10,
  message: { message: "Too many email requests. Please try again later." },
  standardHeaders: true,
  legacyHeaders: false,
});

const bomItemSchema = z.object({
  id: z.string().max(100),
  name: z.string().max(200),
  qty: z.number().int().min(0).max(9999),
  foc: z.boolean().optional()
});

const licenseTierSchema = z.object({
  id: z.string().max(100),
  name: z.string().max(100),
  maxDoors: z.number().int().min(0),
  maxUsers: z.number().int().min(0),
  maxOperators: z.number().int().min(0),
  desc: z.string().max(500).optional()
});

const sendEmailSchema = z.object({
  to: z.string().email().max(255),
  cc: z.array(z.string().email().max(255)).max(10).optional(),
  note: z.string().max(2000).optional().default(""),
  language: z.enum(["es", "en", "pt"]).optional().default("es"),
  calculatedBOM: z.object({
    bom: z.array(bomItemSchema).max(50),
    selected: licenseTierSchema,
    alternative: z.object({
      bom: z.array(bomItemSchema).max(50),
      selected: licenseTierSchema,
      reason: z.string().max(500)
    }).optional()
  }),
  meta: z.object({
    projectName: z.string().max(200).optional().default(""),
    client: z.string().max(200).optional().default(""),
    clientType: z.string().max(100).optional().default(""),
    country: z.string().max(100).optional().default(""),
    contactFirst: z.string().max(100).optional().default(""),
    contactLast: z.string().max(100).optional().default(""),
    phone: z.string().max(50).optional().default(""),
    email: z.string().max(255).optional().default(""),
    authorized: z.boolean().optional().default(false),
    bs2Version: z.string().max(50).optional().default(""),
    activationCode: z.string().max(100).optional().default(""),
    bs2TaLicense: z.string().max(100).optional().default(""),
    bs2VisitorLicense: z.boolean().optional().default(false),
    dashboardFile: z.string().max(500).optional().default(""),
    dashboardFileData: z.string().optional().default(""),
    versionFile: z.string().max(500).optional().default(""),
    versionFileData: z.string().optional().default(""),
    licenseFile: z.string().max(500).optional().default(""),
    licenseFileData: z.string().optional().default(""),
    hardwareChecked: z.boolean().optional().default(false)
  }),
  inputs: z.object({
    scenario: z.enum(["new", "migration", ""]),
    users: z.number().int().min(0).max(10000000),
    doors: z.number().int().min(0).max(100000),
    devices: z.number().int().min(0).max(100000),
    operators: z.number().int().min(0).max(1000),
    video: z.number().int().min(0).max(10000),
    qr: z.number().int().min(0).max(10000),
    wireless: z.number().int().min(0).max(10000),
    tnaUsers: z.number().int().min(0).max(10000000),
    mcsServers: z.number().int().min(0).max(100).optional(),
    activationCode: z.string().max(100).optional()
  })
});

const translations = {
  es: {
    title: "BioStar X - Cálculo de Licenciamiento",
    autoGenerated: "Reporte generado automáticamente",
    projectInfo: "Información del Proyecto",
    project: "Proyecto",
    client: "Cliente",
    country: "País",
    clientType: "Tipo de Cliente",
    scenario: "Escenario",
    scenarioNew: "Proyecto Nuevo",
    scenarioMigration: "Migración BioStar 2",
    sizing: "Dimensionamiento",
    users: "Usuarios",
    doors: "Puertas",
    devices: "Dispositivos",
    operators: "Operadores",
    recommendedTier: "Tier Recomendado",
    maxCapacity: "Capacidad máxima",
    bom: "Bill of Materials (BOM)",
    partNumber: "Part Number",
    description: "Descripción",
    quantity: "Cantidad",
    note: "Nota",
    foc: "Sin Costo (FOC)",
    withCost: "Con Costo",
    alternativeOption: "Opción Alternativa",
    alternativeReason: "Costo optimizado mediante paquetes de expansión",
    clientNote: "Nota del cliente",
    footer: "Este correo fue enviado desde el Calculador BioStar X de Suprema.",
    moreInfo: "Para más información, contactar a",
    disclaimer: "Aviso: Esta herramienta es una guía de ayuda para preventa. Los resultados requieren validación oficial de Suprema antes de cualquier proceso de compra.",
    notSpecified: "Sin especificar"
  },
  en: {
    title: "BioStar X - Licensing Calculation",
    autoGenerated: "Automatically generated report",
    projectInfo: "Project Information",
    project: "Project",
    client: "Client",
    country: "Country",
    clientType: "Client Type",
    scenario: "Scenario",
    scenarioNew: "New Project",
    scenarioMigration: "BioStar 2 Migration",
    sizing: "Sizing",
    users: "Users",
    doors: "Doors",
    devices: "Devices",
    operators: "Operators",
    recommendedTier: "Recommended Tier",
    maxCapacity: "Maximum capacity",
    bom: "Bill of Materials (BOM)",
    partNumber: "Part Number",
    description: "Description",
    quantity: "Quantity",
    note: "Note",
    foc: "Free of Charge (FOC)",
    withCost: "With Cost",
    alternativeOption: "Alternative Option",
    alternativeReason: "Cost optimized through expansion packages",
    clientNote: "Client note",
    footer: "This email was sent from the BioStar X Calculator by Suprema.",
    moreInfo: "For more information, please contact your country sales representative.",
    disclaimer: "Notice: This tool is a presales guidance aid. Results require official Suprema validation before any purchase process.",
    notSpecified: "Not specified"
  },
  pt: {
    title: "BioStar X - Cálculo de Licenciamento",
    autoGenerated: "Relatório gerado automaticamente",
    projectInfo: "Informações do Projeto",
    project: "Projeto",
    client: "Cliente",
    country: "País",
    clientType: "Tipo de Cliente",
    scenario: "Cenário",
    scenarioNew: "Novo Projeto",
    scenarioMigration: "Migração BioStar 2",
    sizing: "Dimensionamento",
    users: "Usuários",
    doors: "Portas",
    devices: "Dispositivos",
    operators: "Operadores",
    recommendedTier: "Tier Recomendado",
    maxCapacity: "Capacidade máxima",
    bom: "Bill of Materials (BOM)",
    partNumber: "Part Number",
    description: "Descrição",
    quantity: "Quantidade",
    note: "Nota",
    foc: "Sem Custo (FOC)",
    withCost: "Com Custo",
    alternativeOption: "Opção Alternativa",
    alternativeReason: "Custo otimizado por meio de pacotes de expansão",
    clientNote: "Nota do cliente",
    footer: "Este e-mail foi enviado do Calculador BioStar X da Suprema.",
    moreInfo: "Para mais informações, contate",
    disclaimer: "Aviso: Esta ferramenta é um guia de auxílio para pré-venda. Os resultados requerem validação oficial da Suprema antes de qualquer processo de compra.",
    notSpecified: "Não especificado"
  }
};

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {

  app.post("/api/send-email", emailLimiter, async (req, res) => {
    try {
      const parseResult = sendEmailSchema.safeParse(req.body);
      
      if (!parseResult.success) {
        return res.status(400).json({ 
          message: "Invalid request data",
          errors: parseResult.error.flatten().fieldErrors
        });
      }

      const { to, cc, note, language, calculatedBOM, meta, inputs } = parseResult.data;
      const t = translations[language];

      const { bom, selected, alternative } = calculatedBOM;

      const isMigration = inputs.scenario === "migration";
      const bomHtml = bom.map((item) => {
        const noteLabel = isMigration ? (item.foc ? `<span style="color: #16a34a; font-weight: bold;">${t.foc}</span>` : `<span style="color: #d97706; font-weight: bold;">${t.withCost}</span>`) : "";
        return `<tr>
          <td style="padding: 8px; border: 1px solid #e5e5e5;">${escapeHtml(item.id)}</td>
          <td style="padding: 8px; border: 1px solid #e5e5e5;">${escapeHtml(item.name)}</td>
          <td style="padding: 8px; border: 1px solid #e5e5e5; text-align: center;">${item.qty}</td>
          ${isMigration ? `<td style="padding: 8px; border: 1px solid #e5e5e5; text-align: center;">${noteLabel}</td>` : ""}
        </tr>`;
      }).join("");

      let alternativeHtml = "";
      if (alternative) {
        const altBomHtml = alternative.bom.map((item) => {
          const noteLabel = isMigration ? (item.foc ? `<span style="color: #16a34a; font-weight: bold;">${t.foc}</span>` : `<span style="color: #d97706; font-weight: bold;">${t.withCost}</span>`) : "";
          return `<tr>
            <td style="padding: 8px; border: 1px solid #e5e5e5;">${escapeHtml(item.id)}</td>
            <td style="padding: 8px; border: 1px solid #e5e5e5;">${escapeHtml(item.name)}</td>
            <td style="padding: 8px; border: 1px solid #e5e5e5; text-align: center;">${item.qty}</td>
            ${isMigration ? `<td style="padding: 8px; border: 1px solid #e5e5e5; text-align: center;">${noteLabel}</td>` : ""}
          </tr>`;
        }).join("");

        alternativeHtml = `
          <h3 style="color: #0047FF; margin-top: 30px;">${t.alternativeOption}: BioStar X ${escapeHtml(alternative.selected.name)}</h3>
          <p style="font-style: italic; color: #666;">${t.alternativeReason}</p>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <thead>
              <tr style="background: #f5f5f5;">
                <th style="padding: 10px; border: 1px solid #e5e5e5; text-align: left;">${t.partNumber}</th>
                <th style="padding: 10px; border: 1px solid #e5e5e5; text-align: left;">${t.description}</th>
                <th style="padding: 10px; border: 1px solid #e5e5e5; text-align: center;">${t.quantity}</th>
                ${isMigration ? `<th style="padding: 10px; border: 1px solid #e5e5e5; text-align: center;">${t.note}</th>` : ""}
              </tr>
            </thead>
            <tbody>
              ${altBomHtml}
            </tbody>
          </table>
        `;
      }

      const noteHtml = note ? `
        <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; margin-top: 20px;">
          <strong>${t.clientNote}:</strong>
          <p style="margin: 10px 0 0 0;">${escapeHtml(note)}</p>
        </div>
      ` : "";

      const emailHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
          </style>
        </head>
        <body style="padding: 20px; max-width: 800px; margin: 0 auto;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #B12944; margin-bottom: 5px;">${t.title}</h1>
            <p style="color: #666;">${t.autoGenerated}</p>
          </div>

          <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <h2 style="color: #333; margin-top: 0;">${t.sizing}</h2>
            <table style="width: 100%;">
              <tr>
                <td style="padding: 5px 0;"><strong>${t.users}:</strong></td>
                <td>${inputs.users.toLocaleString()}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0;"><strong>${t.doors}:</strong></td>
                <td>${inputs.doors}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0;"><strong>${t.devices}:</strong></td>
                <td>${inputs.devices}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0;"><strong>${t.operators}:</strong></td>
                <td>${inputs.operators}</td>
              </tr>
            </table>
          </div>

          <h2 style="color: #B12944;">${t.recommendedTier}: BioStar X ${escapeHtml(selected.name)}</h2>
          <p>
            <strong>${t.maxCapacity}:</strong> 
            ${selected.maxDoors} ${t.doors.toLowerCase()} | 
            ${selected.maxUsers.toLocaleString()} ${t.users.toLowerCase()} | 
            ${selected.maxOperators} ${t.operators.toLowerCase()}
          </p>

          <h3 style="color: #333;">${t.bom}</h3>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <thead>
              <tr style="background: #B12944; color: white;">
                <th style="padding: 10px; border: 1px solid #B12944; text-align: left;">${t.partNumber}</th>
                <th style="padding: 10px; border: 1px solid #B12944; text-align: left;">${t.description}</th>
                <th style="padding: 10px; border: 1px solid #B12944; text-align: center;">${t.quantity}</th>
                ${isMigration ? `<th style="padding: 10px; border: 1px solid #B12944; text-align: center;">${t.note}</th>` : ""}
              </tr>
            </thead>
            <tbody>
              ${bomHtml}
            </tbody>
          </table>

          ${alternativeHtml}
          ${noteHtml}

          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e5e5; text-align: center; color: #666; font-size: 12px;">
            <p>
              ${t.footer}<br>
              ${language === 'en' ? t.moreInfo : `${t.moreInfo} <a href="mailto:latam@supremainc.com" style="color: #B12944;">latam@supremainc.com</a>`}
            </p>
            <p style="margin-top: 15px;">
              <em>${t.disclaimer}</em>
            </p>
          </div>
        </body>
        </html>
      `;

      const projectName = meta.projectName || (language === "en" ? "Project" : language === "pt" ? "Projeto" : "Proyecto");
      
      const attachments: { filename: string; content: string; encoding: string; contentType?: string }[] = [];
      const fileFields = [
        { name: meta.dashboardFile, data: meta.dashboardFileData },
        { name: meta.versionFile, data: meta.versionFileData },
        { name: meta.licenseFile, data: meta.licenseFileData },
      ];
      for (const f of fileFields) {
        if (f.name && f.data) {
          const match = f.data.match(/^data:([^;]+);base64,(.+)$/);
          if (match) {
            attachments.push({
              filename: f.name,
              content: match[2],
              encoding: 'base64',
              contentType: match[1],
            });
          }
        }
      }

      const mailOptions = {
        from: `"Calculador BioStar X" <${process.env.GMAIL_USER}>`,
        to,
        cc: cc && cc.length > 0 ? cc.join(", ") : undefined,
        subject: `${t.title}: ${escapeHtml(projectName)}`,
        html: emailHtml,
        attachments,
      };

      await transporter.sendMail(mailOptions);

      res.json({ success: true });
    } catch (error) {
      console.error("Email send error:", error);
      res.status(500).json({ 
        message: error instanceof Error ? error.message : "Failed to send email" 
      });
    }
  });

  return httpServer;
}
